swagger: '2.0'

info:
  version: "1.0.0"
  title: Behmeh API
  description: |
    Behmeh Spike

    ### Usage:
    1. /selector get by CSS selector

host: "6qt8emo1x8.execute-api.us-east-1.amazonaws.com"
basePath: "/sandbox"
schemes:
  - "https"

paths:

  /selector:
    get:
      description: |
        Get by CSS selector

      parameters:
        - name: url
          in: query
          description: URL to be scraped
          required: true
          type: string
        - name: selector
          in: query
          description: CSS selector
          required: false
          type: string

      produces:
        - application/json; charset=utf-8
      responses:
        200:
          description: TBA
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        500:
          description: Server error
          headers:
            Access-Control-Allow-Origin:
              type: "string"
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
          204:
            statusCode: "204"
          5\d{2}:
            statusCode: "500"

        requestTemplates:
          application/json: >
            {
              "url" : "$input.params('url')"

              #set($selector = $input.params('selector'))
              #if($selector && $selector.length() != 0)
              	, "selector" : "$selector"
              #end
            }
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:626197060234:function:behmeh/invocations"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws"

definitions:
  Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        description:
          type: string